---
dependency: []
galaxy_info:
  author: Your Name
  description: Check and fix RPM database issues automatically
  company: ''
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
  - '7'
  - '8'
  - '9'
    - name: Fedora
      versions:
        - all
  # categories property removed (not supported)
